### ISSUE TITLE
Fails when branch name contains a slash

### ISSUE THREAD

**Issue by PeterHatch** [room118solutions/git-rails-database-branch-hook#2]
I found when switching from a branch named 'feature/description-of-feature', I'll get an error along the lines of:

Saving state of development database on 'feature/description-of-feature' branch...sh: 1: cannot create /home/peterh/project/.db_branch_dumps/database_development-feature/description-of-feature: Directory nonexistent
failed!
Failed to dump database. Halting.

**Comment by cgunther** [comment]
Sorry for the delay, I just released a fix for this.
